### PR TITLE
bump shellcheck version

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by caarlos0** [comment]
@bastelfreak thanks, but you're actually lowering the version, right?

**Comment by bastelfreak** [comment]
ah my bad, the newest version is v0.4.3, I misread this. Sadly the new version isn't packaged yet.

**Comment by caarlos0** [comment]
@bastelfreak yeah :/

**Comment by caarlos0** [comment]
Hey @bastelfreak, check #19 :beers:

**Pull request closed without merging**
